name: Databricks CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  databricks-ci:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Install Databricks CLI
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks version

      # 3. Validate bundle
      - name: Validate Databricks Bundle
        run: |
          databricks bundle validate

      # 4. Deploy to prod (since only main exists)
      - name: Deploy Databricks Bundle
        run: |
          databricks bundle deploy -t prod
